spring:

 
  mvc:
    view:
      prefix: "/WEB-INF/views"
      suffix: ".jsp"

  datasource:
   url: jdbc:mysql://localhost:3306/spring?characterEncoding=UTF-8&serverTimezone=UTC
   #username: root
   #password: 1234
   #driver-class-name: org.mariadb.jdbc.Driver
   username: root
   password: ckatkflekd!99
   driver-class-name: com.mysql.cj.jdbc.Driver
  
  session:
    jdbc:
      initialize-schema: always
      
      
server:
  port: 8080

  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      
    jsp:
      init-parameters:
       development: true
    session:
      timeout: 7200
   
  error:
    whitelabel:
      enabled: false
    
    
mybatis:
  type-aliases-package: com.lcomputerspring3.example.domain
  mapper-locations: mapper/**/*.xml


  
    